version: '3.5'

services:
  db:
    image: final_project_db
    container_name: final_project_db
    build:
      context: ./postgresql
    env_file: 
      - ./login.env
    ports:
      - 5432:5432
    networks:
      - final_proj_db_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s  

  api:
    image: final_project_api
    container_name: final_project_api
    build:
      context: ./webapp
    env_file: 
      - ./login.env
    ports:
      - 8000:8000
    networks:
      - final_proj_db_network
    depends_on:
      db:
        condition: service_healthy

networks:
  final_proj_db_network:
    name: final_proj_db_network