version: '3.5'

services:
  db:
    image: final_project_db
    container_name: final_project_db
    build:
      context: ./postgresql
    env_file: 
      - ./login.env
    ports:
      - 5001:5432
    networks:
      - final_proj_db_network

networks:
  final_proj_db_network:
    name: final_proj_db_network