version: '3.5'

services:
  front:
    image: final_project_front
    container_name: final_project_front
    build:
      context: ./frontend
    ports:
      - 5002:8080
    restart: unless-stopped
    network_mode: bridge

  api:
    image: final_project_api
    container_name: final_project_api
    build:
      context: ./webapp
    ports:
      - 5001:8000
    restart: unless-stopped
    network_mode: bridge